# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6efc32a43bd04af938a52e114cdbc310dc8aff2b3ecf2262eb3f82d0c87b064557a194db590a748240355bd9f5919bdc270ad30f9138e37ef7d63cc7f78aabf

test:
  secret_key_base: 678498a8647f67ffadbdd9a5bbd51a67c56d732c5a6a33cd76fbd7fc77fc394b89fcdc85b86fa03903af8567b547df47bba801d7394eed97dc9cd088af76b500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
